import type { Metadata } from 'next';
// import Header from '../components/Core/Header';
// import Footer from '../components/Core/Footer';
// These styles apply to every route in the application
import '../styles/globals.css';
import StyledComponentsRegistry from '@/lib/app-registry/antd';
import GlobalLayout from '../components/layout';
import SWRProvider from '@/components/providers/SWRProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <StyledComponentsRegistry>
                    <SWRProvider>
                        <GlobalLayout>{children}</GlobalLayout>
                    </SWRProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
